version: '3.8'

services:
  app:
    build: .
    container_name: go-redis-mvp
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - redis
    networks:
      - go-redis-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - go-redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:

networks:
  go-redis-net:
    driver: bridge